version: '2.1'

services:
  db:
    image: postgres:9.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: serve
    volumes:
      - ./:/app/
      - ${GOOGLE_APPLICATION_CREDENTIALS:-./setup.py}:/app/.credentials
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/.credentials
      - PROJECT_ID
      - TMP_AVRO_PATH
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
