FROM python:2-slim

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    DEVELOPMENT=1 \
    POSTGRES_HOST=db \
    POSTGRES_USER=postgres \
    PORT=5000 \
    # No boto. See https://github.com/travis-ci/travis-ci/issues/7940
    BOTO_CONFIG=/dev/null \
    DB_TEST_URL="dbname=postgres user=postgres host=db" \
    PYTHONPATH=$PYTHONPATH:.

EXPOSE $PORT

# python-slim base image has missing directories required for psql install
RUN mkdir -p /usr/share/man/man1
RUN mkdir -p /usr/share/man/man7

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libsnappy-dev liblzma-dev g++ redis-server curl libpq-dev bzip2 libffi-dev \
        python-numpy python-pandas python-scipy wget ca-certificates openssl libssl-dev \
        postgresql-9.4 postgresql-contrib-9.4 postgresql-server-dev-9.4 \
        openjdk-7-jdk && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install spark
RUN wget https://d3kbcqa49mib13.cloudfront.net/spark-2.0.2-bin-hadoop2.7.tgz -O /opt/spark.tgz && \
    tar -xzf /opt/spark.tgz -C /opt

ENV SPARK_HOME=/opt/spark-2.0.2-bin-hadoop2.7 \
    PYTHONPATH=/opt/spark-2.0.2-bin-hadoop2.7/python:/opt/spark-2.0.2-bin-hadoop2.7/python/lib/py4j-0.10.3-src.zip

# add a non-privileged user for installing and running the application
RUN mkdir /app && \
    chown 10001:10001 /app && \
    groupadd --gid 10001 app && \
    useradd --no-create-home --uid 10001 --gid 10001 --home-dir /app app

# Install Python dependencies
COPY requirements/*.txt /tmp/requirements/

# Switch to /tmp to install dependencies outside home dir
WORKDIR /tmp
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements/all.txt

# Switch back to home directory
WORKDIR /app
COPY . /app
RUN chown -R 10001:10001 /app

USER 10001

ENTRYPOINT ["/bin/bash", "/app/bin/run"]

CMD ["web-dev"]
