FROM python:2-stretch

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    DEVELOPMENT=1 \
    POSTGRES_HOST=db \
    POSTGRES_USER=postgres \
    PORT=5000 \
    DB_PORT=5432 \
    # No boto. See https://github.com/travis-ci/travis-ci/issues/7940
    BOTO_CONFIG=/dev/null \
    DB_TEST_URL="dbname=postgres user=postgres host=db" \
    PYTHONPATH=$PYTHONPATH:.

EXPOSE $PORT

# Install Java
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends openjdk-8-jdk

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
        gcc awscli net-tools \
        libsnappy-dev liblzma-dev g++ curl libpq-dev bzip2 libffi-dev \
        python-numpy python-pandas python-scipy wget ca-certificates openssl libssl-dev \
        postgresql && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# add a non-privileged user for installing and running the application
RUN mkdir /app && \
    chown 10001:10001 /app && \
    groupadd --gid 10001 app && \
    useradd --no-create-home --uid 10001 --gid 10001 --home-dir /app app

# Install Python dependencies
COPY requirements/*.txt /tmp/requirements/

# Switch to /tmp to install dependencies outside home dir
WORKDIR /tmp
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements/all.txt

ENV PYSPARK_PYTHON=python \
    SPARK_HOME=/usr/local/lib/python2.7/site-packages/pyspark

# Switch back to home directory
WORKDIR /app
COPY . /app
RUN chown -R 10001:10001 /app

USER 10001

ENTRYPOINT ["/bin/bash", "/app/bin/run"]

CMD ["serve"]
