version: '2'

services:
  db:
    image: postgres:9.4

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - $PWD:/app
    depends_on:
      - db
    links:
      - db
    command: web-dev
