- name: setup local development environment
  hosts: all

  vars:
    - spark_version: 2.0.2
    - postgresql_version: 9.4

  pre_tasks:
    - name: install packages
      apt: name={{item}} state=installed update_cache=yes cache_valid_time=3600
      with_items:
        - libsnappy-dev
        - liblzma-dev
        - g++
        - redis-server
        - python-numpy
        - python-pandas
        - python-scipy
        - wget
        - ca-certificates

    - name: get the current release codename for adding apt repositories
      shell: "lsb_release -cs"
      register: codename

    - name: add apt repository for postgresql
      apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ {{ codename.stdout }}-pgdg main" state=present

    - name: trust the postgresql apt repository signing key
      apt_key: id=ACCC4CF8 url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

    - name: install postgresql packages
      apt: name={{item}} state=installed update_cache=yes
      with_items:
        - libpq-dev
        - postgresql-{{postgresql_version}}
        - postgresql-contrib-{{postgresql_version}}
        - postgresql-server-dev-{{postgresql_version}}

    - name: stop postgres service
      service: name=postgresql state=stopped enabled=no

    - name: configure postgresql
      lineinfile: dest={{ansible_env.HOME}}/.bashrc regexp="^export.*postgresql" line="export PATH=/usr/lib/postgresql/{{postgresql_version}}/bin:$PATH"

    - name: configure postgresql language settings
      lineinfile: dest={{ansible_env.HOME}}/.bashrc regexp="^export\s+LC_CTYPE" line="export LC_CTYPE=en_US.UTF-8"

  roles:
    - role: anaconda
    - role: spark

  post_tasks:
    # travis_build_dir can be set on the command line with Ansible's `-e` flag

    - name: setup project dependencies on Vagrant
      pip: name=/vagrant state=present executable={{ansible_env.HOME}}/miniconda2/bin/pip extra_args='--editable'
      when: not travis_build_dir is defined

    - name: setup project dependencies on TravisCI
      pip: name={{travis_build_dir}} state=present executable={{ansible_env.HOME}}/miniconda2/bin/pip
      when: travis_build_dir is defined
